[package]
name = "now_playing"
version = "0.1.0"
authors = ["@thorning_m <matthewthorning@gmail.com>"]
edition = "2018"

[dependencies]
ws = "0.8.1"
serde_json = "1.0"
serde = { version = "1.0.91", features = ["derive"] }
