[package]
name = "now_playing"
version = "1.0.0"
authors = ["@thorning_m <matthewthorning@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0.91", features = ["derive"] }
dirs = "1.0.5"
os_type="2.2"
